version: "3.7"
services:
    frontend:
        image: node:14-alpine
        command: "npm run dev"
        env_file:
            - ./.env
        ports:
            - "5000:5000"
            - "3000:3000"
        volumes:
            - ./:/app
        working_dir: /app
    database:
        image: "mongo"
        ports:
            - "27017:27017"
        expose:
            - 27017
        volumes:
            - ./docker/setup-database.sh:/docker-entrypoint-initdb.d/setup-database.sh
            - ./videos/:/videos
            - ./database:/database
            - database-data:/data/db

volumes:
    database-data:
